"""added 'websocket_id' to guest users

Revision ID: 696dbf33d32a
Revises: 76a151607a8e
Create Date: 2020-01-25 10:52:31.845467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696dbf33d32a'
down_revision = '76a151607a8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('websocket_id', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'websocket_id')
    # ### end Alembic commands ###
